### ISSUE TITLE
Major: Android users logged out after a few minutes

### ISSUE THREAD

**Issue by jorgtron** [pmusaraj/discourse-mobile-single-site-app#10] opened 2018-03-19 00:06 UTC
To replicate: leave app open for 5-ish minutes on android device and close app. You'll have to log in again on next open. Reported by multiple users, but I haven't seen it myself.

**Comment by pmusaraj** [comment] 2018-03-22 17:28
I could not reproduce this on an emulator. I loaded the app after a few weeks of not running it, and it logged back in to the site correctly. 

My emulator is running API 27. It's possible this is an issue with a specific version/flavour of Android. 

I will be able to test tomorrow with a real device (older than API 27) and report back. 

It would be useful to have more information on the devices of the users that have seen this problem, specifically the Android version on each device.

**Comment by jorgtron** [comment] 2018-03-22 22:21
I have these reports so far:
- 2 users using an HTC U11 (android 8.0.0)
- 1 using F8132 (android 7.1.1)
- 1 using EVA-L09 (android 7.0)

**Comment by pmusaraj** [comment] 2018-03-22 23:59
Ok, I can reproduce now on Android 8 (API 26) emulator.

**Comment by pmusaraj** [comment] 2018-03-23 01:49
Alright, I think I found the issue. Users do not get logged out, but the app doesn't correctly store the state in some cases, which means that users will see the initial login screen (even if they are actually logged in to the app). 

This is now fixed, I think. And current users can click on "Skip" and this will show their current session and fix the issue for further sessions. 

Thanks!

**Closed by pmusaraj** 2018-03-23 01:49 UTC
